COMMON_SUBDOMAINS = [
    "www", "mail", "ftp", "admin", "dev", "api", "webmail", "server", "ns1", "ns2",
    "blog", "shop", "forum", "support", "test", "beta", "portal", "secure", "vpn",
    "cdn", "images", "img", "static", "assets", "media", "docs", "wiki", "git",
    "staging", "demo", "app", "apps", "mobile", "m", "wap", "news", "press",
    "careers", "jobs", "hr", "payroll", "staff", "employee", "intranet", "internal",
    "corp", "corporate", "office", "login", "signin", "register", "signup", "auth",
    "account", "accounts", "profile", "dashboard", "panel", "cpanel", "whm",
    "phpmyadmin", "pma", "mysql", "db", "database", "adminer", "webmin",
    "mailserver", "smtp", "pop3", "imap", "exchange", "owa", "webmail",
    "video", "tv", "stream", "live", "radio", "music", "audio",
    "download", "dl", "files", "upload", "share", "cloud", "storage",
    "backup", "backup1", "backup2", "mirror", "mirror1", "mirror2",
    "help", "faq", "kb", "knowledgebase", "docs", "documentation",
    "status", "monitor", "monitoring", "stats", "analytics",
    "search", "find", "lookup", "whois", "dns",
    "shop", "store", "ecommerce", "cart", "checkout",
    "forum", "community", "discourse", "slack", "teams",
    "support", "helpdesk", "ticket", "tickets", "contact",
    "careers", "jobs", "recruit", "hire",
    "press", "media", "pr", "newsroom",
    "legal", "privacy", "terms", "tos",
    "about", "info", "information", "company",
    "blog", "news", "updates", "announcements",
    "events", "calendar", "schedule",
    "services", "solutions", "products",
    "partners", "affiliates", "resellers",
    "investors", "ir", "finance", "financial",
    "api", "api1", "api2", "api3",
    "graphql", "rest", "soap",
    "cdn", "assets", "static",
    "img", "images", "photos",
    "video", "media", "audio",
    "dev", "development", "staging",
    "test", "testing", "qa",
    "sandbox", "demo", "preview",
    "beta", "alpha", "experimental",
    "prod", "production", "live",
    "stage", "staging", "preprod",
    "uat", "useracceptance",
    "training", "learn", "education",
    "course", "courses", "class",
    "campus", "school", "university",
    "library", "lib", "archive",
    "museum", "gallery", "exhibit",
    "expo", "show", "fair",
    "conference", "event", "meeting",
    "summit", "forum", "congress",
    "workshop", "seminar", "webinar",
    "office", "branch", "location",
    "nyc", "london", "tokyo", "paris",
    "berlin", "sydney", "singapore",
    "us", "uk", "eu", "asia",
    "americas", "emea", "apac",
    "north", "south", "east", "west",
    "central", "global", "worldwide",
]
