# VEX Subdomain Discovery — 500+ Common Subdomains
# Sources: SecLists, subdomain-center, brute-force lists

COMMON_SUBDOMAINS = [
    # Core
    "www", "mail", "ftp", "admin", "blog", "webmail", "webdisk", "ns1", "ns2",
    "api", "dev", "test", "stage", "staging", "app", "beta", "demo", "m",
    "shop", "store", "support", "help", "forum", "community",
    # Infrastructure
    "cdn", "static", "assets", "media", "img", "images", "css", "js",
    "download", "uploads", "files", "backup", "db", "database",
    "mysql", "postgres", "redis", "mongo", "elastic",
    "git", "svn", "jenkins", "jira", "confluence", "wiki",
    "monitor", "monitoring", "status", "stats", "logs", "log",
    # Security
    "vpn", "secure", "ssl", "gateway", "proxy", "firewall",
    "auth", "login", "register", "signup", "sso", "oauth",
    "captcha", "recaptcha", "verify", "validate",
    # Development
    "gitlab", "github", "bitbucket", "code", "devops",
    "build", "ci", "cd", "integration", "deploy",
    "sandbox", "playground", "lab", "labs",
    # Management
    "dashboard", "manager", "manage", "management",
    "panel", "control", "cpanel", "whm", "plesk",
    "phpmyadmin", "pma", "adminer", "phpPgAdmin",
    # Communication
    "chat", "talk", "voice", "video", "meet", "meeting",
    "zoom", "teams", "slack", "discord", "irc",
    # Mail
    "smtp", "pop3", "imap", "mailgun", "sendgrid", "postfix",
    "newsletter", "mailchimp", "list", "lists",
    # Analytics
    "analytics", "tracking", "track", "pixel", "counter",
    "piwik", "matomo", "google-analytics",
    # Social
    "facebook", "twitter", "instagram", "linkedin", "youtube",
    "social", "share", "like", "follow",
    # Content
    "wiki", "knowledgebase", "kb", "faq", "docs",
    "documentation", "manual", "guide", "tutorial",
    "news", "press", "events", "calendar",
    # Services
    "service", "services", "api", "gateway", "webhook",
    "callback", "notification", "notify", "alert",
    "webmail", "office365", "outlook", "exchange",
    # CRMs
    "crm", "sales", "salesforce", "hubspot", "zoho",
    "sugarcrm", "vtiger", "suitecrm",
    # ERP
    "erp", "sap", "oracle", "dynamics", "navision",
    "odoo", "openerp", "tryton",
    # Specific
    "remote", "access", "portal", "extranet", "intranet",
    "mobile", "mobi", "mob", "touch", "responsive",
    "cloud", "aws", "azure", "gcp", "digitalocean",
    "server", "node", "cluster", "worker", "queue",
    "search", "catalog", "index", "sitemap", "feed",
    "rss", "atom", "xml", "json", "csv", "export", "import",
    "invoice", "billing", "payment", "checkout", "cart",
    "wifi", "guest", "hotspot", "portal",
    "survey", "poll", "vote", "rating", "review",
    "job", "career", "careers", "hr", "employee",
    "partner", "partners", "affiliate", "reseller",
    "legal", "privacy", "terms", "dmca", "copyright",
]

ADDITIONAL_SUBDOMAINS = [
    # Extended list
    "0", "1", "2", "3", "4", "5", "6", "7", "8", "9",
    "a", "b", "c", "d", "e", "f", "g", "h", "i", "j",
    "k", "l", "m", "n", "o", "p", "q", "r", "s", "t",
    "u", "v", "w", "x", "y", "z",
    "aa", "bb", "cc", "dd", "ee", "ff", "gg", "hh", "ii",
    "jj", "kk", "ll", "mm", "nn", "oo", "pp", "qq", "rr",
    "ss", "tt", "uu", "vv", "ww", "xx", "yy", "zz",
    "abc", "test1", "test2", "test3", "test4", "test5",
    "dev1", "dev2", "dev3", "dev4", "dev5",
    "stg", "staging1", "staging2", "staging3",
    "prod", "production", "prod1", "prod2",
    "backup1", "backup2", "backup3",
    "db1", "db2", "db3", "db-master", "db-slave",
    "web1", "web2", "web3", "web4", "web5",
    "app1", "app2", "app3", "app4", "app5",
    "node1", "node2", "node3",
    "redis1", "redis2", "redis3",
    "mq", "rabbitmq", "kafka", "zookeeper",
    "rancher", "kubernetes", "k8s", "docker",
    "swarm", "mesos", "nomad", "consul",
    "vault", "etcd", "minio", "s3",
    "gcs", "blob", "storage", "archive",
    "cache", "varnish", "squid", "traffic",
    "lb", "loadbalancer", "haproxy", "nginx",
    "apache", "iis", "tomcat", "weblogic",
    "wildfly", "jboss", "glassfish", "jetty",
    "solr", "lucene", "elasticsearch", "kibana",
    "logstash", "graylog", "splunk", "sumo",
    "nagios", "zabbix", "icinga", "prometheus",
    "grafana", "cacti", "munin", "observium",
    "librenms", "netbox", "phpipam", "racktables",
    "puppet", "chef", "ansible", "salt",
    "terraform", "packer", "vagrant", "docker-compose",
    "jenkins", "travis", "circleci", "gitlab-ci",
    "teamcity", "bamboo", "drone", "buddy",
    "sonar", "sonarqube", "codeclimate", "codacy",
    "nexus", "artifactory", "jfrog", "maven",
    "npm", "pypi", "rubygems", "nuget",
    "packagist", "composer", "cargo", "hex",
    "dockerhub", "docker-registry", "ecr", "gcr",
    "quay", "harbor", "portus", "registry",
    "ipfs", "filecoin", "arweave", "sia",
    "tor", "i2p", "freenet", "zeronet",
    "mta", "mx1", "mx2", "mx3", "mx4",
    "relay", "mail-relay", "mail-gateway",
    "antispam", "spam", "spamassassin",
    "clamav", "amavis", "dkim", "dmarc",
    "spf", "domainkeys", "opendkim",
    "ldap", "ldaps", "openldap", "389",
    "radius", "freeradius", "diameter",
    "tacacs", "tacacs+", "acs",
    "splunk", "sumologic", "logz", "papertrail",
    "logentries", "loggly", "sentry", "rollbar",
    "bugsnag", "airbrake", "raygun", "honeybadger",
    "pagerduty", "opsgenie", "victorops",
    "servicenow", "freshdesk", "zendesk",
    "jira", "confluence", "bitbucket",
    "trello", "asana", "basecamp", "notion",
    "slack", "teams", "discord", "rocket",
    "mattermost", "riot", "element", "keybase",
    "phone", "call", "voip", "sip",
    "asterisk", "freeswitch", "kamailio",
    "jitsi", "bigbluebutton", "openmeetings",
    "webex", "gotomeeting", "adobeconnect",
    "lime", "leaf", "node", "edge",
    "akamai", "cloudflare", "fastly", "cloudfront",
    "ddos", "mitigation", "blackhole",
    "honeypot", "honeynet", "canary",
    "threat", "threatintel", "intel",
    "phish", "phishing", "malware", "botnet",
    "c2", "command", "control", "panel",
    "scanning", "exploit", "vuln", "vulnerability",
    "pentest", "pentesting", "bugbounty", "bounty",
    "report", "disclosure", "security",
]
